apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  #namespace: prueba
spec:
  hard:
    pods: 2
    requests.cpu: 1
    requests.memory: 1Gi
    limits.cpu: 2
    limits.memory: 2Gi
